// <auto-generated />
using System;
using APForums.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APForums.Server.Migrations
{
    [DbContext(typeof(ForumsDbContext))]
    [Migration("20230717104227_Create-User-Table")]
    partial class CreateUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APForums.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Course")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("DOB");

                    b.Property<string>("DegreeType")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Department")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Email")
                        .HasComputedColumnSql("[Tp_Number] + '@mail.apu.edu.my'", false);

                    b.Property<string>("Enrollment")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Phone");

                    b.Property<string>("TPNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("TpNumber");

                    b.HasKey("Id");

                    b.HasIndex("TPNumber")
                        .IsUnique();

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
